services:
  postgres-db:
    image: postgres:16-alpine
    container_name: pry-todo-db
    environment:
      POSTGRES_USER: pry_user
      POSTGRES_PASSWORD: pry_password
      POSTGRES_DB: pry_todo
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pry-todo-backend
    ports:
      - "8002:8002"
    depends_on:
      - postgres-db
    volumes:
      - backend_data:/app/data
      - .build/backend/.env:/app/.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: pry-todo-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - .build/frontend/.env:/app/.env

volumes:
  pg_data:
  backend_data: